name: Run Playwright Tests on Deployment Success

on:
  push:
    branches:
      - action
  deployment_status:
    types:
      - success

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Choose the appropriate Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npm test
